// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kinokz/ent/film"
	"kinokz/ent/predicate"
	"kinokz/ent/user"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FilmQuery is the builder for querying Film entities.
type FilmQuery struct {
	config
	ctx         *QueryContext
	order       []film.OrderOption
	inters      []Interceptor
	predicates  []predicate.Film
	withAuthor  *UserQuery
	withManager *UserQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FilmQuery builder.
func (fq *FilmQuery) Where(ps ...predicate.Film) *FilmQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FilmQuery) Limit(limit int) *FilmQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *FilmQuery) Offset(offset int) *FilmQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FilmQuery) Unique(unique bool) *FilmQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FilmQuery) Order(o ...film.OrderOption) *FilmQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryAuthor chains the current query on the "author" edge.
func (fq *FilmQuery) QueryAuthor() *UserQuery {
	query := (&UserClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(film.Table, film.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, film.AuthorTable, film.AuthorColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManager chains the current query on the "manager" edge.
func (fq *FilmQuery) QueryManager() *UserQuery {
	query := (&UserClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(film.Table, film.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, film.ManagerTable, film.ManagerColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Film entity from the query.
// Returns a *NotFoundError when no Film was found.
func (fq *FilmQuery) First(ctx context.Context) (*Film, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{film.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FilmQuery) FirstX(ctx context.Context) *Film {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Film ID from the query.
// Returns a *NotFoundError when no Film ID was found.
func (fq *FilmQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{film.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FilmQuery) FirstIDX(ctx context.Context) int64 {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Film entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Film entity is found.
// Returns a *NotFoundError when no Film entities are found.
func (fq *FilmQuery) Only(ctx context.Context) (*Film, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{film.Label}
	default:
		return nil, &NotSingularError{film.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FilmQuery) OnlyX(ctx context.Context) *Film {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Film ID in the query.
// Returns a *NotSingularError when more than one Film ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FilmQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{film.Label}
	default:
		err = &NotSingularError{film.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FilmQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Films.
func (fq *FilmQuery) All(ctx context.Context) ([]*Film, error) {
	ctx = setContextOp(ctx, fq.ctx, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Film, *FilmQuery]()
	return withInterceptors[[]*Film](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FilmQuery) AllX(ctx context.Context) []*Film {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Film IDs.
func (fq *FilmQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if fq.ctx.Unique == nil && fq.path != nil {
		fq.Unique(true)
	}
	ctx = setContextOp(ctx, fq.ctx, "IDs")
	if err = fq.Select(film.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FilmQuery) IDsX(ctx context.Context) []int64 {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FilmQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FilmQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FilmQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FilmQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FilmQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FilmQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FilmQuery) Clone() *FilmQuery {
	if fq == nil {
		return nil
	}
	return &FilmQuery{
		config:      fq.config,
		ctx:         fq.ctx.Clone(),
		order:       append([]film.OrderOption{}, fq.order...),
		inters:      append([]Interceptor{}, fq.inters...),
		predicates:  append([]predicate.Film{}, fq.predicates...),
		withAuthor:  fq.withAuthor.Clone(),
		withManager: fq.withManager.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FilmQuery) WithAuthor(opts ...func(*UserQuery)) *FilmQuery {
	query := (&UserClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withAuthor = query
	return fq
}

// WithManager tells the query-builder to eager-load the nodes that are connected to
// the "manager" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FilmQuery) WithManager(opts ...func(*UserQuery)) *FilmQuery {
	query := (&UserClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withManager = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Film.Query().
//		GroupBy(film.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FilmQuery) GroupBy(field string, fields ...string) *FilmGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FilmGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = film.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Film.Query().
//		Select(film.FieldName).
//		Scan(ctx, &v)
func (fq *FilmQuery) Select(fields ...string) *FilmSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &FilmSelect{FilmQuery: fq}
	sbuild.label = film.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FilmSelect configured with the given aggregations.
func (fq *FilmQuery) Aggregate(fns ...AggregateFunc) *FilmSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FilmQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !film.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FilmQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Film, error) {
	var (
		nodes       = []*Film{}
		_spec       = fq.querySpec()
		loadedTypes = [2]bool{
			fq.withAuthor != nil,
			fq.withManager != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Film).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Film{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(fq.modifiers) > 0 {
		_spec.Modifiers = fq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withAuthor; query != nil {
		if err := fq.loadAuthor(ctx, query, nodes, nil,
			func(n *Film, e *User) { n.Edges.Author = e }); err != nil {
			return nil, err
		}
	}
	if query := fq.withManager; query != nil {
		if err := fq.loadManager(ctx, query, nodes, nil,
			func(n *Film, e *User) { n.Edges.Manager = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FilmQuery) loadAuthor(ctx context.Context, query *UserQuery, nodes []*Film, init func(*Film), assign func(*Film, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Film)
	for i := range nodes {
		fk := nodes[i].AuthorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "author_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fq *FilmQuery) loadManager(ctx context.Context, query *UserQuery, nodes []*Film, init func(*Film), assign func(*Film, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Film)
	for i := range nodes {
		fk := nodes[i].ManagerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "manager_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (fq *FilmQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	if len(fq.modifiers) > 0 {
		_spec.Modifiers = fq.modifiers
	}
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FilmQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(film.Table, film.Columns, sqlgraph.NewFieldSpec(film.FieldID, field.TypeInt64))
	_spec.From = fq.sql
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fq.path != nil {
		_spec.Unique = true
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, film.FieldID)
		for i := range fields {
			if fields[i] != film.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if fq.withAuthor != nil {
			_spec.Node.AddColumnOnce(film.FieldAuthorID)
		}
		if fq.withManager != nil {
			_spec.Node.AddColumnOnce(film.FieldManagerID)
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FilmQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(film.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = film.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range fq.modifiers {
		m(selector)
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (fq *FilmQuery) Modify(modifiers ...func(s *sql.Selector)) *FilmSelect {
	fq.modifiers = append(fq.modifiers, modifiers...)
	return fq.Select()
}

// FilmGroupBy is the group-by builder for Film entities.
type FilmGroupBy struct {
	selector
	build *FilmQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FilmGroupBy) Aggregate(fns ...AggregateFunc) *FilmGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FilmGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FilmQuery, *FilmGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FilmGroupBy) sqlScan(ctx context.Context, root *FilmQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FilmSelect is the builder for selecting fields of Film entities.
type FilmSelect struct {
	*FilmQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FilmSelect) Aggregate(fns ...AggregateFunc) *FilmSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FilmSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FilmQuery, *FilmSelect](ctx, fs.FilmQuery, fs, fs.inters, v)
}

func (fs *FilmSelect) sqlScan(ctx context.Context, root *FilmQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (fs *FilmSelect) Modify(modifiers ...func(s *sql.Selector)) *FilmSelect {
	fs.modifiers = append(fs.modifiers, modifiers...)
	return fs
}
